name: Build Android
on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64"]
      fail-fast: false
    name: "Build for ${{matrix.arch}}"
    runs-on: ubuntu-22-04
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3.7 python3.7-dev python3-pip \
            glslang-tools \
            golang-lukechampine-blake3-dev \
            librust-blake3-dev \
            b3sum \
            libxrandr-dev libxxf86vm-dev \
            libxcb-*-dev libx11-xcb-dev \
            libxfixes-dev libdrm-dev libx11-dev \
            libudev-dev libpciaccess-dev \
            libepoxy-dev \
            libxcb-glx0-dev \
            libegl1-mesa-dev \
            libgles2-mesa-dev \
            libwayland-dev \
            libvulkan-dev \
            libgbm-dev \
            pkg-config

          python3.7 -m pip install meson==0.47.0 ninja==1.8.2

      - name: Clone Mesa repository
        run: |
          git clone https://gitlab.freedesktop.org/lyudess/panfrost-mesa.git
          cd panfrost-mesa
          git checkout winsys-meson

      - name: Set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
          unzip android-ndk-r20-linux-x86_64.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r20
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Setup Build Files
        run: |
          cp android-* .
          envsubst <android-${{matrix.arch}} >build-crossfile
          meson setup "build-android" \
            --prefix=/tmp/pan \
            --cross-file "build-crossfile" \
            -Dplatforms=x11 \
            -Dllvm=disabled \
            -Dvulkan-drivers= \
            -Dgallium-drivers=panfrost,swrast \
            -Dbuildtype=release

      - name: Build and Install
        run: |
          ninja -C "build-android" install

      - name: Upload Libraries
        uses: actions/upload-artifact@v4
        with:
          name: panfrost_${{matrix.arch}}
          path: /tmp/pan
